# Generated by ./configure on Mon Apr  6 21:46:21 CST 2026
# Do not edit -- re-run ./configure instead.

# Compiler
CC = cc
HOST_OS = Linux

# Installation directories
PREFIX      = /usr/local
EXEC_PREFIX = /usr/local
BINDIR      = /usr/local/bin
LIBDIR      = /usr/local/lib
INCLUDEDIR  = /usr/local/include/dixon
MANDIR      = /usr/local/share/man/man1

# Default link mode: dynamic | static-all
DEFAULT_LINK_MODE = dynamic

# Library search paths
FLINT_INCLUDE_PATH = /usr/local/include
FLINT_LIB_PATH = /usr/local/lib
PML_INCLUDE_PATH = /usr/local/include
PML_LIB_PATH = /usr/local/lib

# Detection results
FLINT_HEADER_CHECK = yes
FLINT_HEADER_DIR = /usr/local/include
FLINT_VERSION = 3.4.0
FLINT_DYNAMIC_LIB_CHECK = yes
FLINT_STATIC_LIB_CHECK = yes
FLINT_SO_PATH = /usr/local/lib/libflint.so
FLINT_A_PATH = /usr/local/lib/libflint.a
PML_HEADER_CHECK = yes
PML_HEADER_PREFIX = pml/
PML_HEADER_DIR = /usr/local/include/pml
NMOD_POLY_MAT_UTILS_CHECK = yes
NMOD_POLY_MAT_EXTRA_CHECK = yes
PML_DYNAMIC_LIB_CHECK = yes
PML_STATIC_LIB_CHECK = yes
PML_SO_PATH = /usr/local/lib/libpml.so
PML_A_PATH = /usr/local/lib/libpml.a
FLINT_DIR_EXISTS = yes
PML_DIR_EXISTS = yes
PML_AVAILABLE = yes

# System library search paths (for info/debug targets)
SYSTEM_LIB_PATHS = /usr/local/lib /usr/lib /home/ideal/crypto/Tongsuo/lib64 /usr/lib64 /usr/local/lib64 /lib /lib64 /usr/lib/x86_64-linux-gnu

# Derived flags
ARCH_CFLAGS = -march=native
LTO_CFLAGS = -flto=auto
LTO_LDFLAGS = -flto=auto
OPENMP_AVAILABLE = yes
OPENMP_CFLAGS = -fopenmp
OPENMP_LDFLAGS = -fopenmp
INCLUDE_FLAGS = -I./include -I/usr/local/include -I/usr/include -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/include/x86_64-linux-gnu -I/usr/local/include/pml
FLINT_FLAGS = -DHAVE_FLINT
PML_FLAGS = -DHAVE_PML

# Library linking
FLINT_LIBS = -L/usr/local/lib -lflint
FLINT_STATIC_LIBS = /usr/local/lib/libflint.a
PML_LIBS = /usr/local/lib/libpml.so
PML_STATIC_LIBS = /usr/local/lib/libpml.a
SYSTEM_LIBS = -lmpfr -lgmp -lm -lpthread -lstdc++

# RPATH
RPATH_FLAGS = -Wl,-rpath,/usr/local/lib -Wl,-rpath,. -Wl,-rpath,/usr/local/lib

# Shared library build
SHARED_LIB_EXT = so
SHARED_LDFLAGS = -shared

# AddressSanitizer
ENABLE_ASAN = no
ASAN_CFLAGS = 
ASAN_LDFLAGS = 
